query pageQuery($filter: PostFilter, $sort: String) {
  ...LayoutQueryFragment
  postConnection(filter:$filter, sort: $sort) {
    edges {
      node {
         seo {
          title
          description
          url
        }
        id
        date
        title
        excerpt
        heroImg
        author {
          ... on Author {
            ...AuthorParts
          }
        }
        category {
          ... on Category {
            ...CategoryParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

query allBlogQuery($filter: PostFilter, $sort: String) {
  postConnection(filter:$filter, sort: $sort) {
    edges {
      node {
         category {
          ... on Category {
            ...CategoryParts
          }
        }
        title
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    ...PostParts
    _sys {
      filename
    }
    author {
      ... on Author {
        name
        avatar
      }
    }
  }
}
